// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiBackEnd_Customers.Models;

public partial class Customer
{
    public int IdCustomer { get; set; }

    public string User { get; set; }

    public string Name { get; set; }

    public string Title { get; set; }

    public string Cellphone { get; set; }

    public string Email { get; set; }

    public string ContactType { get; set; }
}